
---
title: "Does Foreign Aid Improve Educational Outcomes? Evidence from Uganda"
author: 
  - Riana Ramonjamanana
  - Charlene R. Ramos
date: "`r Sys.Date()`"

output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    keep_tex: false

header-includes:
  - \usepackage{amsmath, amssymb}
  - \usepackage{booktabs}
  - \usepackage{caption}      
  - \usepackage{float}
  - \usepackage{geometry}    
  - \usepackage{lmodern}     
  - \usepackage{placeins} 
  - \usepackage{setspace}    
  - \usepackage{threeparttable}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{} % clear default header/footer
  - \cfoot{\thepage} % page number on bottom-right
  - \renewcommand{\headrulewidth}{0pt}
---

```{r setup, include=FALSE}
# install.packages(c("kableExtra","knitr","rmarkdown","tidyverse","tinytex","webshot2"))
# tinytex::install_tinytex() 

# ------------------------------- INSTRUCTIONS ------------------------------- #
# 1. Uncomment R chunk labeled data_aid. This cleans and analyzes the 
# international aid data. When finish, comment this chunk out again. The PDF 
# file won't render otherwise. 
# 2. Run R chunk labeled render to generate the PDF table.

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r data_aid, include=FALSE}
# 
# library(kableExtra)
# library(tidyverse)
# library(webshot2)
# 
# # setwd('/Users/charleneramos/Documents/Git/econ250project')
# 
# # fmt <- function(x) formatC(x, format = "f", big.mark = ",", digits = 0)
# 
# level_1a <- read_csv('/Users/charleneramos/Documents/Git/econ250project/data/raw/UgandaAIMS_GeocodedResearchRelease_Level1_v1.4.1/data/level_1a.csv')
# # locations <- read_csv('data/raw/UgandaAIMS_GeocodedResearchRelease_Level1_v1.4.1/data/locations.csv')
# # projects <- read_csv('data/raw/UgandaAIMS_GeocodedResearchRelease_Level1_v1.4.1/data/projects.csv')
# transactions <- read_csv('/Users/charleneramos/Documents/Git/econ250project/data/raw/UgandaAIMS_GeocodedResearchRelease_Level1_v1.4.1/data/transactions.csv')
# 
# df <- transactions %>%
#   filter(transaction_value_code == 'D') %>% # filter for disbursement
#   select(-c('transaction_isodate', 'transaction_currency','transaction_value_code')) # drop unnecessary columns; note USD currency
# 
# df <- merge(df, level_1a, by = 'project_id')
# # df <- merge(df, projects, by = 'project_id')
# # df <- merge(df, locations, by = 'project_id')
# 
# df <- df %>%
#   filter(transactions_end_year >= 2013 & transactions_end_year <= 2017) %>% # filter for years 2013-2017
#   filter(location_type_code == 'ADM2') %>% # filter for ADM2 locations
#   distinct() %>%
#   arrange(project_id) %>%
#   select(c('project_id', 'project_location_id', everything()))
# 
# all_transaction <- df %>%
#   group_by(transactions_end_year) %>%
#   summarise(
#     mean = mean(transaction_value),
#     sd = sd(transaction_value),
#     n = n(),
#     min = min(transaction_value),
#     max = max(transaction_value)
#   ) %>%
#   mutate(region = 'All', variable = 'transaction') %>%
#   rename(year = transactions_end_year) %>%
#   select(c('variable','region'), everything())
# 
# all_total_disbursement<- df %>%
#   group_by(transactions_end_year) %>%
#   summarise(
#     mean = mean(total_disbursements),
#     sd = sd(total_disbursements),
#     n = n(),
#     min = min(total_disbursements),
#     max = max(total_disbursements)
#   ) %>%
#   mutate(region = 'All', variable = 'total_disbursement') %>%
#   rename(year = transactions_end_year) %>%
#   select(c('variable','region'), everything())
# 
# all_even_disbursement<- df %>%
#   group_by(transactions_end_year) %>%
#   summarise(
#     mean = mean(even_split_disbursements),
#     sd = sd(even_split_disbursements),
#     n = n(),
#     min = min(even_split_disbursements),
#     max = max(even_split_disbursements)
#   ) %>%
#   mutate(region = 'All', variable = 'even_split_disbursement') %>%
#   rename(year = transactions_end_year) %>%
#   select(c('variable','region'), everything())
# 
# region_transaction <- df %>%
#   group_by(transactions_end_year, place_name) %>%
#   summarise(
#     mean = mean(transaction_value),
#     sd = sd(transaction_value),
#     n = n(),
#     min = min(transaction_value),
#     max = max(transaction_value)
#   ) %>%
#   mutate(variable = 'transaction') %>%
#   rename(region = place_name, year = transactions_end_year) %>%
#   select(c('variable','region'), everything()) %>%
#   arrange(region)
# 
# region_total_disbursement <- df %>%
#   group_by(transactions_end_year, place_name) %>%
#   summarise(
#     mean = mean(total_disbursements),
#     sd = sd(total_disbursements),
#     n = n(),
#     min = min(total_disbursements),
#     max = max(total_disbursements)
#   ) %>%
#   mutate(variable = 'total_disbursement') %>%
#   rename(region = place_name, year = transactions_end_year) %>%
#   select(c('variable','region'), everything()) %>%
#   arrange(region)
# 
# region_even_disbursement <- df %>%
#   group_by(transactions_end_year, place_name) %>%
#   summarise(
#     mean = mean(even_split_disbursements),
#     sd = sd(even_split_disbursements),
#     n = n(),
#     min = min(even_split_disbursements),
#     max = max(even_split_disbursements)
#   ) %>%
#   mutate(variable = 'even_split_disbursement') %>%
#   rename(region = place_name, year = transactions_end_year) %>%
#   select(c('variable','region'), everything()) %>%
#   arrange(region)
# 
# df_stats <- bind_rows(all_transaction, all_total_disbursement, all_even_disbursement, region_transaction, region_total_disbursement, region_even_disbursement)
# 
# df_stats <- df_stats %>%
#   arrange(variable)
# 
# write_csv(df_stats, '/Users/charleneramos/Documents/Git/econ250project/data/int/summary_stats_aid.csv')
# 
# df_sum_stat <- df_stats %>%
#   mutate(across(where(is.numeric), ~ format(.x, big.mark = ",", scientific = FALSE))) %>%
#   mutate(year = as.numeric(gsub(',', '', year))) %>%
#   filter(region == 'All') %>%
#   kbl() %>%                       # <— kableExtra’s wrapper; detects format
#   kable_styling(full_width = FALSE)
# 
# save_kable(df_sum_stat, '/Users/charleneramos/Documents/Git/econ250project/output/summary_stats_aid.html')
# webshot('/Users/charleneramos/Documents/Git/econ250project/output/summary_stats_aid.html', '/Users/charleneramos/Documents/Git/econ250project/output/summary_stats_aid.png',
#         selector = "table",      # crops tightly to the table
#         zoom = 2,                # higher resolution
#         vwidth = 2000,           # width of the browser window
#         vheight = 3000           # height — increase if your table is tall
# )
# 
# df_stat_mean <- df_stats %>%
#   group_by(variable, region, year) %>%
#   mutate(across(where(is.numeric), ~ format(.x, big.mark = ",", scientific = FALSE))) %>%
#   mutate(year = as.numeric(gsub(',', '', year))) %>%
#   select(c('variable', 'region', 'year', 'mean', 'sd')) %>%
#   filter(region == 'All') %>%
#   mutate(
#     # format each mean–sd pair as a string
#     mean_sd = paste0(
#       mean,
#       "<br>(",
#       sd,
#       ")"
#     )
#   ) %>%
#   select(variable, region, year, mean_sd) %>%
#   pivot_wider(
#     names_from  = year,
#     values_from = mean_sd
#   ) %>%
#   select(c('variable', 'region', '2013', '2014', '2015', '2016', '2017')) %>%
#   kbl(escape = FALSE, align = "lcccc", caption = "Mean (SD) by Year") %>%
#   kable_styling(full_width = FALSE)
# 
# save_kable(df_stat_mean, '/Users/charleneramos/Documents/Git/econ250project/output/summary_mean_aid.html')
# webshot('/Users/charleneramos/Documents/Git/econ250project/output/summary_mean_aid.html', '/Users/charleneramos/Documents/Git/econ250project/output/summary_mean_aid.png',
#         selector = "table",      # crops tightly to the table
#         zoom = 2,                # higher resolution
#         vwidth = 2000,           # width of the browser window
#         vheight = 3000           # height — increase if your table is tall
# )
# 
# 
# df_stat_mean_region <- df_stats %>%
#   group_by(region, year) %>%
#   mutate(across(where(is.numeric), ~ format(.x, big.mark = ",", scientific = FALSE))) %>%
#   mutate(year = as.numeric(gsub(',', '', year))) %>%
#   filter(variable == 'even_split_disbursement') %>%
#   select(c('region', 'year', 'mean', 'sd')) %>%
#   mutate(
#     # format each mean–sd pair as a string
#     mean_sd = paste0(
#       mean,
#       "<br>(",
#       sd,
#       ")"
#     )
#   ) %>%
#   select(region, year, mean_sd) %>%
#   pivot_wider(
#     names_from  = year,
#     values_from = mean_sd
#   ) %>%
#   select(c('region', '2013', '2014', '2015', '2016', '2017')) %>%
#   kbl(escape = FALSE, align = "lcccc", caption = "Mean (SD) by Year and Region") %>%
#   kable_styling(full_width = FALSE)
# 
# save_kable(df_stat_mean_region, '/Users/charleneramos/Documents/Git/econ250project/output/summary_mean_aid_region.html')
# webshot('/Users/charleneramos/Documents/Git/econ250project/output/summary_mean_aid_region.html', '/Users/charleneramos/Documents/Git/econ250project/output/summary_mean_aid_region.png',
#         selector = "table",      # crops tightly to the table
#         zoom = 2,                # higher resolution
#         vwidth = 2000,           # width of the browser window
#         vheight = 3000           # height — increase if your table is tall
# )

```




```{=latex}



\section{Introduction}
In this paper, we study the impact of foreign aid on the educational outcomes of working-age adults in Uganda. The relationship between the amount of aid received and the economic growth of developing countries remains an open, important question among researchers and policymakers. Using spatial data from William \& Mary’s GeoQuery platform, we trace the geographic boundaries of various projects and their reach during 2014 to 2017. This allows us to pursue identification through a Barthik instrument constructed with industry and employment shares by district. To formulate the second stage of the regression, we utilize data on educational attainment available at the smallest level of disaggregation for interpretation against the instrumental variable.

\section{Data}
The project, locations, and transactions provided in the foreign aid dataset was extracted using the GeoQuery platform, which was initially funded by USAID and continues to be managed by William \& Mary as an initiative under their development research lab called AidData. The combined dataset contains all geocoded projects from the Government of Uganda's Aid Information Management System (AIMS) (also known as Uganda's Aid Management Platform or UAMP). It follows 565 geocoded projects across 2,426 locations from as early as the late 1970s through the mid-2010s. In total, the database accounts for more than \$$7.5$ billion in disbursements. The scope of the projects span a wide range of targeted sectors such as health, energy, and education with additional detailed information on other relevant variables including donors, start date, end date, and total commitments. 

\section{Methodology}
\section{Results}

\begin{table}[!htbp]
\centering
\caption{Summary Statistics by Year}
\begin{threeparttable}
\begin{tabular}{lcccc}
\toprule
\multicolumn{1}{l}{} & \textbf{2014} & \textbf{2015} & \textbf{2016} & \textbf{2017} \\
\midrule
\multicolumn{5}{l}{\textbf{Education Outcomes}} \\
\quad Primary gross enrollment rate & 125.09 & 111.10 & 128.81 & 115.44 \\
& (43.34) & (26.91) & (66.62) & (30.33) \\~\\
\quad Secondary gross enrollment rate & 29.62 & 23.61 & 28.64 & 24.29 \\
& (15.89) & (13.49) & (19.20) & (12.41)\\
\midrule
\quad N & 123 & 123 & 123 & 123 \\
\midrule
\addlinespace
\multicolumn{5}{l}{\textbf{International Aid}} \\
\quad Total transaction amount & `r format(all_transaction$mean[all_transaction$year == 2014], big.mark = ",", scientific = FALSE)` 
& `r format(all_transaction$mean[all_transaction$year == 2015], big.mark = ",", scientific = FALSE)` 
& `r format(all_transaction$mean[all_transaction$year == 2016], big.mark = ",", scientific = FALSE)` 
& `r format(all_transaction$mean[all_transaction$year == 2017], big.mark = ",", scientific = FALSE)`\\

& (`r format(all_transaction$sd[all_transaction$year == 2014], big.mark = ",", scientific = FALSE)`) 
& (`r format(all_transaction$sd[all_transaction$year == 2015], big.mark = ",", scientific = FALSE)`) 
& (`r format(all_transaction$sd[all_transaction$year == 2016], big.mark = ",", scientific = FALSE)`) 
& (`r format(all_transaction$sd[all_transaction$year == 2017], big.mark = ",", scientific = FALSE)`)\\~\\

\quad Even-split disbursement & `r format(all_even_disbursement$mean[all_even_disbursement$year == 2014], big.mark = ",", scientific = FALSE)` 
& `r format(all_even_disbursement$mean[all_even_disbursement$year == 2015], big.mark = ",", scientific = FALSE)` 
& `r format(all_even_disbursement$mean[all_even_disbursement$year == 2016], big.mark = ",", scientific = FALSE)` 
& `r format(all_even_disbursement$mean[all_even_disbursement$year == 2017], big.mark = ",", scientific = FALSE)`\\

& (`r format(all_even_disbursement$sd[all_even_disbursement$year == 2014], big.mark = ",", scientific = FALSE)`)  
& (`r format(all_even_disbursement$sd[all_even_disbursement$year == 2015], big.mark = ",", scientific = FALSE)`) 
& (`r format(round(all_even_disbursement$sd[all_even_disbursement$year == 2016]), big.mark = ",", scientific = FALSE)`) 
& (`r format(all_even_disbursement$sd[all_even_disbursement$year == 2017], big.mark = ",", scientific = FALSE)`)\\~\\

\quad Total disbursement & `r format(all_total_disbursement$mean[all_total_disbursement$year == 2014], big.mark = ",", scientific = FALSE)` 
& `r format(all_total_disbursement$mean[all_total_disbursement$year == 2015], big.mark = ",", scientific = FALSE)` 
& `r format(all_total_disbursement$mean[all_total_disbursement$year == 2016], big.mark = ",", scientific = FALSE)` 
& `r format(all_total_disbursement$mean[all_total_disbursement$year == 2017], big.mark = ",", scientific = FALSE)` \\

& (`r format(all_total_disbursement$sd[all_total_disbursement$year == 2014], big.mark = ",", scientific = FALSE)`) 
& (`r format(all_total_disbursement$sd[all_total_disbursement$year == 2015], big.mark = ",", scientific = FALSE)`) 
& (`r format(all_total_disbursement$sd[all_total_disbursement$year == 2016], big.mark = ",", scientific = FALSE)`)
& (`r format(all_total_disbursement$sd[all_total_disbursement$year == 2017], big.mark = ",", scientific = FALSE)`)\\
\midrule
\quad N & `r format(all_transaction$n[all_transaction$year == 2014], big.mark = ",", scientific = FALSE)` 
& `r format(all_transaction$n[all_transaction$year == 2015], big.mark = ",", scientific = FALSE)` 
& `r format(all_transaction$n[all_transaction$year == 2016], big.mark = ",", scientific = FALSE)` 
& `r format(all_transaction$n[all_transaction$year == 2017], big.mark = ",", scientific = FALSE)`\\
\bottomrule
\end{tabular}
\begin{tablenotes}\small
\item Notes: Values are means with standard deviations in parentheses. Aid data are from Uganda's Aid Management Platform that tracks geocoded projects' disbursements. Even-split disbursement represent evenly allocated total disbursement amounts between project start and end years. Education data are from the Uganda Bureau of Statistics.
\end{tablenotes}
\end{threeparttable}
\end{table}
\FloatBarrier

\section{Discussion}
\section{Conclusion}
\section{References}




```

```{r render, include=FALSE, eval=FALSE}
rmarkdown::render(
  "/Users/charleneramos/Documents/Git/econ250project/code/table_means.Rmd",
  output_format = "pdf_document",
  output_dir = "/Users/charleneramos/Documents/Git/econ250project/output/"
)

rmarkdown::render(
  "/Users/charleneramos/Documents/Git/econ250project/code/vsp_draft.Rmd",
  output_format = "pdf_document",
  output_dir = "/Users/charleneramos/Documents/Git/econ250project/output/"
)
```